### ISSUE TITLE
should we implement login_check ?

### ISSUE THREAD

**Issue by stloc** [zitadel/example-symfony-oidc#4]
I have tested your full example with my custum OIDC (other than zitadel) and after login I have many redirections
and finally "MSIS9604: An error occurred. The authorization server was not able to fulfill the request"

I only created a login_check route with a simple Response ?

![image](https://github.com/zitadel/example-symfony-oidc/assets/4832070/cf0d2fce-2077-4f9f-8274-62ba112170ad)

**Comment by muhlemmer** [comment]
> should we implement login_check ?

AFAIK not.

Are you running into this issue after you cloned this repo, or is it something that happens in your project only?
Can you please add steps to reproduce, based on this repo for example:

> 1. Forked this repo
> 2. Changed xyz

And append the changes, for example a `git diff` output.

**Comment by stloc** [comment]
I forked to https://github.com/stloc/example-symfony-oidc
change .env locally (vars OIDC_)
and launched `symfony serve` (with tls) : https://localhost:8000
after redirecting to login form anf success login : 
![image](https://github.com/zitadel/example-symfony-oidc/assets/4832070/68ab9544-e0ae-4bdf-a066-9fa2d215d0a2)

**Comment by stloc** [comment]
with a Zitadel project application like https://tlg-zitadel-xxx.zitadel.cloud it works very good !

**Comment by drigolin** [comment]
I receive an error /login_check 
Unable to find the controller for path "/login_check". The route is wrongly configured.
